#!/usr/bin/env sh

yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0
yabai -m config layout bsp
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 1
yabai -m config right_padding 1
yabai -m config window_gap 5
yabai -m config default-desk 5

# Apps
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Fantastical$" manage=off
yabai -m rule --add app="^Stats$" manage=off

# Assign apps to desktops
yabai -m rule --add app="^(Arc|Firefox|Google Chrome)$" space=1
yabai -m rule --add app="^Alacritty$" space=2
yabai -m rule --add app="^(Xcode|VSCodium|IntelliJ IDEA|DataGrip)$" space=3
yabai -m rule --add app="^Kindle$" space=4
yabai -m rule --add app="^Spotify$" space=5
